# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{geonames_local}
<<<<<<< HEAD
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Marcos Piccinini"]
  s.date = %q{2010-03-19}
=======
  s.version = "0.0.5"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Marcos Piccinini"]
  s.date = %q{2010-01-30}
>>>>>>> 95997d8548c72dcb9ae0a5ddaa1c80f0451430bf
  s.default_executable = %q{geonames}
  s.description = %q{Dump and feed a tokyo cabinet for local geonames search}
  s.email = %q{x@nofxx.com}
  s.executables = ["geonames"]
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
<<<<<<< HEAD
     "geonames_local.gemspec",
     "lib/geonames_local.rb",
     "spec/data/tokyo_spec.rb",
     "spec/geonames_local_spec.rb",
     "spec/spec.opts",
     "spec/spec_helper.rb",
=======
     "bin/geonames",
     "geonames_local.gemspec",
     "lib/config/codes.yml",
     "lib/config/geonames.yml",
     "lib/data/cache.rb",
     "lib/data/geoquery.rb",
     "lib/data/postgres.rb",
     "lib/data/shp.rb",
     "lib/data/tokyo.rb",
     "lib/features/city.rb",
     "lib/features/country.rb",
     "lib/features/province.rb",
     "lib/features/road.rb",
     "lib/features/spot.rb",
     "lib/features/zone.rb",
     "lib/geonames_local.rb",
     "lib/work/cli.rb",
     "lib/work/dump.rb",
     "lib/work/export.rb",
     "spec/data/cache_spec.rb",
     "spec/data/postgres_spec.rb",
     "spec/data/shp_spec.rb",
     "spec/data/tokyo_spec.rb",
     "spec/features/road_spec.rb",
     "spec/features/spot_spec.rb",
     "spec/features/zone_spec.rb",
     "spec/geonames_local_spec.rb",
     "spec/spec.opts",
     "spec/spec_helper.rb",
     "spec/work/cli_spec.rb",
>>>>>>> 95997d8548c72dcb9ae0a5ddaa1c80f0451430bf
     "task/benchmark.rb",
     "task/benchmark_cabinet.rb"
  ]
  s.homepage = %q{http://github.com/nofxx/geonames_local}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{Dump and feed a tokyo local geonames db}
  s.test_files = [
<<<<<<< HEAD
    "spec/data/tokyo_spec.rb",
     "spec/spec_helper.rb",
     "spec/geonames_local_spec.rb"
=======
    "spec/data/cache_spec.rb",
     "spec/data/postgres_spec.rb",
     "spec/data/shp_spec.rb",
     "spec/data/tokyo_spec.rb",
     "spec/features/road_spec.rb",
     "spec/features/spot_spec.rb",
     "spec/features/zone_spec.rb",
     "spec/geonames_local_spec.rb",
     "spec/spec_helper.rb",
     "spec/work/cli_spec.rb"
>>>>>>> 95997d8548c72dcb9ae0a5ddaa1c80f0451430bf
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, [">= 1.2.9"])
      s.add_runtime_dependency(%q<tokyotyrant>, [">= 1.10"])
    else
      s.add_dependency(%q<rspec>, [">= 1.2.9"])
      s.add_dependency(%q<tokyotyrant>, [">= 1.10"])
    end
  else
    s.add_dependency(%q<rspec>, [">= 1.2.9"])
    s.add_dependency(%q<tokyotyrant>, [">= 1.10"])
  end
end

